apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx-server
          image: custom_nginx
          imagePullPolicy: Never
          ports:
            - containerPort: 80
            - containerPort: 5000
            - containerPort: 443
          env:
          - name: HOST_PHPMYADMIN
            value: phpmyadmin
          volumeMounts:
            - name: sites-source
              mountPath: /usr/share/nginx/html
      volumes:
      - name: sites-source
        persistentVolumeClaim:
          claimName: sites-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    run: nginx
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: http-phpmyadmin
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  selector:
    app: nginx