apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx-server
          image: custom_nginx
          imagePullPolicy: Never
          ports:
            - containerPort: 80
            - containerPort: 5000
            - containerPort: 443
          env:
          # - name: HOST_PHPMYADMIN
          #   value: phpmyadmin
          # volumeMounts:
          #   - name: sites-source
          #     mountPath: /usr/share/nginx/html
      # volumes:
      # - name: sites-source
      #   persistentVolumeClaim:
      #     claimName: sites-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    run: nginx
spec:
  # type: ClusterIP
  type: NodePort # https://stackoverflow.com/questions/41509439/whats-the-difference-between-clusterip-nodeport-and-loadbalancer-service-types
  ports:
  - port: 32080
    targetPort: 80
    protocol: TCP
    name: http
  - port: 32500
    targetPort: 5000
    protocol: TCP
    name: php-server
  - port: 32443
    targetPort: 443
    protocol: TCP
    name: https
  - port: 32022
    nodePort: 22
    protocol: TCP
    name: ssh-a
  - port: 32222
    nodePort: 2222
    protocol: TCP
    name: ssh-b
  selector:
    app: nginx