apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-svc
  labels:
    app: ft_services
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: ft_services
    tier: backend
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: ft_services
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: ft_services
      tier: backend
  template:
    metadata:
      labels:
        app: ft_services
        tier: backend
    spec:
      restartPolicy: Always
      containers:
      - name: phpmyadmin
        image: custom_php
        imagePullPolicy: Never
        env:
        - name: PMA_HOST
          value: mysql
        ports:
        - containerPort: 80
          hostPort: 5000