apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ft-service-ingress
  labels:
    app: ingress-controller
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - http:
        paths:
        - path: /nginx{1}
          backend:
            serviceName: nginx-svc
            servicePort: 80
        - path: /phpmyadmin
          backend:
            serviceName: phpmyadmin-svc
            servicePort: 5000
  # backend:
  #   serviceName: nginx-svc
  #   servicePort: 80