# apiVersion: networking.k8s.io/v1beta1
# kind: Ingress
# metadata:
#   name: ft-service-ingress
#   labels:
#     app: ingress-controller
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: /$1
# spec:
#   rules:
#   - http:
#       paths:
#         - path: /nginx
#           backend:
#             serviceName: nginx-svc
#             servicePort: 80
#         - path: /wordpress
#           backend:
#             serviceName: wordpress-svc
#             servicePort: 80
# apiVersion: apps/v1
# kind: Ingress
# metadata:
#   annotations:
#     kubernetes.io/ingress.class: nginx
#   name: nginx-ingress
# spec:
#  backend:
#    serviceName: wordpress
#    servicePort: 80