# apiVersion: v1
# kind: Service
# metadata:
#   name: wordpress-svc
#   labels:
#     run: wordpress-svc
# spec:
#   type: ClusterIP
#   ports:
#     - port: 80
#       name: http
#   selector:
#     app: wordpress
#     tier: frontend
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: wp-pv-claim
#   labels:
#     app: wordpress
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 5Gi
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: wordpress-dpl
#   labels:
#     app: wordpress
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: wordpress
#       tier: frontend
#   strategy:
#     type: Recreate
#   template:
#     metadata:
#       labels:
#         app: wordpress
#         tier: frontend
#     spec:
#       containers:
#       - image: wordpress:4.8-apache
#         name: wordpress
#         env:
#         - name: WORDPRESS_DB_HOST
#           value: mysql-dpl
#         - name: WORDPRESS_DB_PASSWORD
#           valueFrom:
#             secretKeyRef:
#               name: mysql-pass
#               key: password
#         - name: DATABASE_USERNAME
#           value: admin
#         - name: DATABASE_PASSWORD
#           valueFrom:
#             secretKeyRef:
#               name: mysql-pass
#               key: password
#         - name: DATABASE_HOST
#           value: root
#         - name: DATABASE_NAME
#           value: wp-db
#         ports:
#         - containerPort: 5050
#           name: wordpress
#         volumeMounts:
#         - name: wordpress-persistent-storage
#           mountPath: /var/www/html
#       volumes:
#       - name: wordpress-persistent-storage
#         persistentVolumeClaim:
#           claimName: wp-pv-claim

apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: ft_services
spec:
  ports:
  - port: 80
  selector:
    app: ft_services
    tier: frontend
  type: LoadBalancer

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pv-claim
  labels:
    app: ft_services
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: ft_services
spec:
  selector:
    matchLabels:
      app: ft_services
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ft_services
        tier: frontend
    spec:
      restartPolicy: Always
      containers:
      - image: custom-wordpress:1.9
        imagePullPolicy: Never
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: mysql
        - name: WORDPRESS_DB_USER
          value: root
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        - name: WORDPRESS_DB_NAME
          value: wordpress
        ports:
        - containerPort: 80
          hostPort: 5050
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wordpress-pv-claim