apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: ft_services
spec:
  clusterIP: None
  ports:
  - port: 3306
  selector:
    app: ft_services
    tier: mysql
  clusterIP: None

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: ft_services
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: ft_services
spec:
  selector:
    matchLabels:
      app: ft_services
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ft_services
        tier: mysql
    spec:
      containers:
      - image: custom_mysql
        imagePullPolicy: Never
        name: mysql
        env:
        - name: MYSQL_USER
          value: root
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        - name: MYSQL_DATABASE
          value: wordpress
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
          - name: mysql-persistent-storage
            mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim